version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - ls -la
      - wget --user=demo@aquasec.com --password=9aV6xpQE https://download.aquasec.com/scanner/4.6.0/scannercli
      - chmod +x scannercli
      - ./scannercli
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=779593258376.dkr.ecr.ap-southeast-1.amazonaws.com/alpine
      - ls -la
  build:
    commands:
      - docker build -t $REPOSITORY_URI:success .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:success
