version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - echo "++ Build number $CODEBUILD_BUILD_NUMBER now ++"
      - wget -q --user=demo@aquasec.com --password=9aV6xpQE https://download.aquasec.com/scanner/4.6.0/scannercli
      - chmod +x scannercli
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=779593258376.dkr.ecr.ap-southeast-1.amazonaws.com/alpine
      - ls -la
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER .
      - ./scannercli scan -H http://demo1102-vm0.aquasec.com -U api -P AquaApiAcccess --local $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER --register --registry "779593258376.dkr.ecr.ap-southeast-1.amazonaws.com"
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
