version: 0.2

phases:
  install:
    runtime-versions:
        docker: 18
  pre_build:
    commands:
      - echo "++ Build number $CODEBUILD_BUILD_NUMBER now ++"
      - wget -q --user=demo@aquasec.com --password=9aV6xpQE https://download.aquasec.com/scanner/6.5.0/scannercli
      - chmod +x scannercli
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=779593258376.dkr.ecr.ap-southeast-1.amazonaws.com/alpine
      - ls -la
      - wget https://get.aquasec.com/aquactl/stable/aquactl
      - chmod +x aquactl
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER .
      - ./scannercli scan -H http://demo2764-vm0.aquaseclabs.com -U api2 -P P@ssw0rd01 --local $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER --htmlfile results.html --register --registry "779593258376.dkr.ecr.ap-southeast-1.amazonaws.com"
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
artifacts:
  files:
    - results.html
